window.support=[
     
            // -------------------------------------------------------------------------------- 
                                              // 5 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20001",
          "name": "Keiko Yukimura, Goddess of Victory",
          "type": "red",
          "class": "ATK",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "400",
          "def": "250",
          "sp": "100",
          "spd": "121",
          "maxpower": "14327",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxsp": "1428",
          "maxdef": "3572",
          "maxspd": "450",
          "skillname": "ATK up",
          "skill": "Increases ATK of equipped unit by 80%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     {
          "id": "20002",
          "name": "Botan, Spiritual Guide",
          "type": "light",
          "class": "SP",
          "rare": "5",
          "power": "1011",
          "hp": "400",
          "atk": "100",
          "def": "175",
          "sp": "525",
          "spd": "111",
          "maxpower": "14317",
          "maxhp": "5712",
          "maxatk": "1428",
          "maxdef": "2496",
          "maxsp": "7496",
          "maxspd": "412",
          "skillname": "SP up",
          "skill": "Increases SP of equipped column by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20013",
          "name": "Great King Enma, Spirit World Ruler",
          "type": "dark",
          "class": "ATK",
          "rare": "5",
          "power": "1011",
          "hp": "500",
          "atk": "400",
          "def": "250",
          "sp": "100",
          "spd": "111",
          "maxpower": "14323",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxdef": "3572",
          "maxsp": "1428",
          "maxspd": "412",
          "skillname": "ATK up",
          "skill": "Increases ATK of equipped column by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20016",
          "name": "Yukina, Dearly Prayer",
          "type": "blue",
          "class": "DEF",
          "rare": "5",
          "power": "1011",
          "hp": "550",
          "atk": "200",
          "def": "325",
          "sp": "200",
          "spd": "119",
          "maxpower": "14324",
          "maxhp": "7856",
          "maxatk": "2856",
          "maxsp": "2856",
          "maxdef": "4640",
          "maxspd": "444",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 43%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 100%/1 time",
          "skillimg": "HEAL",
     },
     {
          "id": "20019",
          "name": "Sakyo, A Game of Aesthetics",
          "type": "dark",
          "class": "SP",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "100",
          "def": "250",
          "sp": "400",
          "spd": "126",
          "maxpower": "14328",
          "maxhp": "7140",
          "maxatk": "1428",
          "maxsp": "5712",
          "maxdef": "3572",
          "maxspd": "468",
          "skillname": "Defense Down",
          "skill": "Decreases DEF of front enemy column by 43%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a weakening effect <hz>Chance:</hz> 80%",
          "skillimg": "DEFdown",
     },
     {
          "id": "20020",
          "name": "Koto, Fiery Commentary",
          "type": "blue",
          "class": "SP",
          "rare": "5",
          "power": "1005",
          "hp": "495",
          "atk": "102",
          "def": "252",
          "sp": "392",
          "spd": "117",
          "maxpower": "14217",
          "maxhp": "7068",
          "maxatk": "1452",
          "maxsp": "3596",
          "maxdef": "5592",
          "maxspd": "434",
          "skillname": "SP Damage Resistance Down",
          "skill": "80% chance to reduce enemy's front column's SP damage resistance by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 80%",
          "skillimg": "SPDMGresistdown",
     },
     {
          "id": "20021",
          "name": "Juri, Sincere Referee",
          "type": "green",
          "class": "ATK",
          "rare": "5",
          "power": "1016",
          "hp": "500",
          "atk": "400",
          "def": "252",
          "sp": "102",
          "spd": "120",
          "maxpower": "14374",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxsp": "3596",
          "maxdef": "1452",
          "maxspd": "446",
          "skillname": "ATK Damage Resistance Down",
          "skill": "80% chance to reduce enemy's front column's ATK damage resistance by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 80%",
          "skillimg": "ATKDMGresistdown",
     },
     {
          "id": "20022",
          "name": "Ruka, Barrier Practitioner",
          "type": "dark",
          "class": "ATK",
          "rare": "5",
          "power": "1011",
          "hp": "492",
          "atk": "522",
          "def": "177",
          "sp": "100",
          "spd": "118",
          "maxpower": "14319",
          "maxhp": "5736",
          "maxatk": "7452",
          "maxsp": "2528",
          "maxdef": "1428",
          "maxspd": "438",
          "skillname": "SP Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against SP damage taken by 43%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "SPDMGresist",
     },
     {
          "id": "20024",
          "name": "Koenma (Youth), Spirit World Royalty",
          "type": "green",
          "class": "DEF",
          "rare": "5",
          "power": "1012",
          "hp": "550",
          "atk": "100",
          "def": "325",
          "sp": "300",
          "spd": "120",
          "maxpower": "14324",
          "maxhp": "7856",
          "maxatk": "1428",
          "maxsp": "4284",
          "maxdef": "4640",
          "maxspd": "446",
          "skillname": "Ressurection",
          "skill": "Revives equipped unit with 29% HP<br><hz>Duration:</hz> instant <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%/1 time",
          "skillimg": "REVIVE",
     },
     {
          "id": "20041",
          "name": "Keiko Yukimura, Promise of Victory",
          "type": "light",
          "class": "SP",
          "rare": "5",
          "power": "1066",
          "hp": "599",
          "atk": "100",
          "def": "249",
          "sp": "406",
          "spd": "120",
          "maxpower": "15096",
          "maxhp": "8552",
          "maxatk": "1428",
          "maxdef": "3552",
          "maxsp": "5796",
          "maxspd": "446",
          "skillname": "SP & DEF Up",
          "skill": "Increases SP of equipped unit by 39% and DEF of all allies by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "SPup",
     },
     {
          "id": "20042",
          "name": "Ruka, Sealing Cursed Barrier",
          "type": "light",
          "class": "SP",
          "rare": "5",
          "power": "1061",
          "hp": "627",
          "atk": "98",
          "def": "245",
          "sp": "393",
          "spd": "118",
          "maxpower": "15031",
          "maxhp": "8952",
          "maxatk": "1400",
          "maxdef": "3500",
          "maxsp": "5612",
          "maxspd": "438",
          "skillname": "ATK Damage Resistance",
          "skill": "Increases ATK Damage Resistance of all allies by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "ATKDMGresist",
     },
     {
          "id": "20050",
          "name": "Botan, Flower Kimono",
          "type": "light",
          "class": "ATK",
          "rare": "5",
          "power": "1018",
          "hp": "407",
          "atk": "536",
          "def": "172",
          "sp": "95",
          "spd": "118",
          "maxpower": "14411",
          "maxhp": "5808",
          "maxatk": "7652",
          "maxsp": "2456",
          "maxdef": "1356",
          "maxspd": "438",
          "skillname": "Critical UP",
          "skill": "Increases Critical Rate of equipped unit by 37%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when an ally dies <hz>Chance:</hz> 100%",
          "skillimg": "CRITup",
     },
     {
          "id": "20055",
          "name": "Puu, Blue Feathered Spirit Beast",
          "type": "blue",
          "class": "SP",
          "rare": "5",
          "power": "1064",
          "hp": "480",
          "atk": "108",
          "def": "176",
          "sp": "528",
          "spd": "121",
          "maxpower": "15059",
          "maxhp": "6852",
          "maxatk": "1544",
          "maxdef": "2508",
          "maxsp": "7536",
          "maxspd": "450",
          "skillname": "Barrier & SP up",
          "skill": "Increases SP by 31% & grants 70% Barrier effect to the equipped unit<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "BARRIEReffect",
     },
     {
          "id": "20063",
          "name": "Hina, Cursed Child's Mother",
          "type": "dark",
          "class": "SP",
          "rare": "5",
          "power": "1015",
          "hp": "396",
          "atk": "100",
          "def": "175",
          "sp": "530",
          "spd": "121",
          "maxpower": "14363",
          "maxhp": "5652",
          "maxatk": "1428",
          "maxdef": "2496",
          "maxsp": "7568",
          "maxspd": "450",
          "skillname": "Taken Damage Up",
          "skill": "100% chance to increase Damage taken of all enemies by 31%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when an ally dies <hz>Chance:</hz> 100%",
          "skillimg": "DMGresist",
     },
     {
          "id": "20064",
          "name": "Rui, Regretful Koorime",
          "type": "green",
          "class": "ATK",
          "rare": "5",
          "power": "1062",
          "hp": "496",
          "atk": "525",
          "def": "178",
          "sp": "99",
          "spd": "120",
          "maxpower": "15032",
          "maxhp": "7080",
          "maxatk": "7496",
          "maxdef": "2540",
          "maxsp": "1412",
          "maxspd": "446",
          "skillname": "Given Damage decrease & ATK up",
          "skill": "Decrease dmg of all enemies by 27% & increase equipped unit's ATK by 39%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a weakening effect <hz>Chance:</hz> 100%",
          "skillimg": "ATKup",
     },
     {
          "id": "20095",
          "name": "Keiko Yukimura, Holy Night Lovely Lady",
          "type": "red",
          "class": "SP",
          "rare": "5",
          "power": "1008",
          "hp": "441",
          "atk": "99",
          "def": "202",
          "sp": "475",
          "spd": "123",
          "maxpower": "14265",
          "maxhp": "6296",
          "maxatk": "1412",
          "maxdef": "2880",
          "maxsp": "6780",
          "maxspd": "456",
          "skillname": "Sp Up",
          "skill": "Increases equipped unit's SP by 51%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 80%",
          "skillimg": "SPup",
     },
     {
          "id": "20096",
          "name": "Yukina, Holy Night Snow Lady",
          "type": "green",
          "class": "DEF",
          "rare": "5",
          "power": "1015",
          "hp": "555",
          "atk": "303",
          "def": "325",
          "sp": "98",
          "spd": "118",
          "maxpower": "14373",
          "maxhp": "7920",
          "maxatk": "4328",
          "maxdef": "4640",
          "maxsp": "1400",
          "maxspd": "438",
          "skillname": "HP Regeneration",
          "skill": "Heals own column by 20%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "REGEN",
     },
     {
          "id": "20098",
          "name": "Maya Kitajima, Faint Love Concept",
          "type": "light",
          "class": "DEF",
          "rare": "5",
          "power": "1018",
          "hp": "558",
          "atk": "99",
          "def": "327",
          "sp": "302",
          "spd": "117",
          "maxpower": "14415",
          "maxhp": "7968",
          "maxatk": "1412",
          "maxdef": "4668",
          "maxsp": "4308",
          "maxspd": "434",
          "skillname": "Defense up",
          "skill": "Increases DEF of equipped row by 50%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "DEFup",
     },
     {
          "id": "20104",
          "name": "Yusuke Urameshi, Wedding White Clothing",
          "type": "blue",
          "class": "ATK",
          "rare": "5",
          "power": "1016",
          "hp": "399",
          "atk": "532",
          "def": "174",
          "sp": "99",
          "spd": "121",
          "maxpower": "14385",
          "maxhp": "5696",
          "maxatk": "7596",
          "maxdef": "2484",
          "maxsp": "1412",
          "maxspd": "450",
          "skillname": "blue Damage up",
          "skill": "Increases blue Damage of equipped column by 22%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "bluedmg",
     },
     {
          "id": "20105",
          "name": "Kurama, Formal White Splendor",
          "type": "red",
          "class": "DEF",
          "rare": "5",
          "power": "1011",
          "hp": "558",
          "atk": "101",
          "def": "323",
          "sp": "296",
          "spd": "121",
          "maxpower": "14301",
          "maxhp": "7968",
          "maxatk": "1440",
          "maxdef": "4608",
          "maxsp": "4224",
          "maxspd": "450",
          "skillname": "Guard Percentage up",
          "skill": "Increases Guard Percentage of equipped column by 36%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "GUARDup",
     },
     {
          "id": "20106",
          "name": "Botan, Summer Guide",
          "type": "blue",
          "class": "SP",
          "rare": "5",
          "power": "1013",
          "hp": "500",
          "atk": "101",
          "def": "249",
          "sp": "402",
          "spd": "118",
          "maxpower": "14341",
          "maxhp": "7140",
          "maxatk": "1440",
          "maxdef": "3552",
          "maxsp": "5736",
          "maxspd": "438",
          "skillname": "Damage up",
          "skill": "Increases equipped unit's Damage by 60%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when using a special <hz>Chance:</hz> 100%",
          "skillimg": "DMGup",
     },
     {
          "id": "20107",
          "name": "Shizuru Kuwabara, Summer Elder Sister",
          "type": "dark",
          "class": "ATK",
          "rare": "5",
          "power": "1011",
          "hp": "504",
          "atk": "402",
          "def": "246",
          "sp": "100",
          "spd": "118",
          "maxpower": "14317",
          "maxhp": "7196",
          "maxatk": "5736",
          "maxdef": "3512",
          "maxsp": "1428",
          "maxspd": "438",
          "skillname": "Critical Damage up",
          "skill": "Increases Critical Damage of equipped column by 50%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 50%",
          "skillimg": "CRITDMGup",
     },
     {
          "id": "20114",
          "name": "Yusuke & Kuwabara, Battle Comrades",
          "type": "blue",
          "class": "ATK",
          "rare": "5",
          "power": "1024",
          "hp": "508",
          "atk": "407",
          "def": "251",
          "sp": "101",
          "spd": "118",
          "maxpower": "14503",
          "maxhp": "7256",
          "maxatk": "5808",
          "maxdef": "3584",
          "maxsp": "1440",
          "maxspd": "438",
          "skillname": "Damage Reduction",
          "skill": "Reduces Taken Damage from own column by 19%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "DMGresist",
     },
     {
          "id": "20115",
          "name": "Kurama & Hiei, Shadow Flower",
          "type": "red",
          "class": "SP",
          "rare": "5",
          "power": "1020",
          "hp": "503",
          "atk": "100",
          "def": "255",
          "sp": "402",
          "spd": "119",
          "maxpower": "14436",
          "maxhp": "7184",
          "maxatk": "1428",
          "maxdef": "3636",
          "maxsp": "5736",
          "maxspd": "444",
          "skillname": "Damage up",
          "skill": "Increases Damage given of equipped column by 19%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "DMGup",
     },
     {
          "id": "20122",
          "name": "Hiei, Cursed Child of Flames",
          "type": "dark",
          "class": "SP",
          "rare": "5",
          "power": "1062",
          "hp": "595",
          "atk": "101",
          "def": "254",
          "sp": "398",
          "spd": "118",
          "maxpower": "15039",
          "maxhp": "8496",
          "maxatk": "1440",
          "maxdef": "3624",
          "maxsp": "5684",
          "maxspd": "438",
          "skillname": "Given Damage up & Burn",
          "skill": "Increases Damage of equipped unit by 47% & inflicts 10% burn to all enemies<br><hz>Duration:</hz> 3 turns/2 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 100%",
          "skillimg": "DMGup",
     },
     {
          "id": "20127",
          "name": "Yukina, Innocent Smile",
          "type": "green",
          "class": "SP",
          "rare": "5",
          "power": "1008",
          "hp": "491",
          "atk": "99",
          "def": "248",
          "sp": "404",
          "spd": "121",
          "maxpower": "14269",
          "maxhp": "7008",
          "maxatk": "1412",
          "maxdef": "3540",
          "maxsp": "5768",
          "maxspd": "450",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 20%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 100%/3 times",
          "skillimg": "HEAL",
     },
     {
          "id": "20135",
          "name": "Hiei, Withered Corpse Costume",
          "type": "red",
          "class": "ATK",
          "rare": "5",
          "power": "1061",
          "hp": "524",
          "atk": "515",
          "def": "175",
          "sp": "98",
          "spd": "117",
          "maxpower": "15033",
          "maxhp": "7484",
          "maxatk": "7352",
          "maxdef": "2496",
          "maxsp": "1400",
          "maxspd": "434",
          "skillname": "ATK DMG & Basic Attack DMG up",
          "skill": "Equipped unit ATK DMG +47% and Basic Attack DMG of all allies +24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after an ally dies <hz>Chance:</hz> 100%",
          "skillimg": "ATKDMGup",
     },
     {
          "id": "20136",
          "name": "Yukina, Saint Costume",
          "type": "dark",
          "class": "DEF",
          "rare": "5",
          "power": "1062",
          "hp": "606",
          "atk": "326",
          "def": "326",
          "sp": "96",
          "spd": "111",
          "maxpower": "15039",
          "maxhp": "8652",
          "maxatk": "4652",
          "maxdef": "4652",
          "maxsp": "1368",
          "maxspd": "412",
          "skillname": "Revive & Basic Attack taken DMG down",
          "skill": "Revives equipped unit with 40% HP and all allies basic attack dmg taken -24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%/1 time",
          "skillimg": "REVIVE",
     },
     {
          "id": "20137",
          "name": "Botan, Holy Night Sparkling Lady",
          "type": "blue",
          "class": "DEF",
          "rare": "5",
          "power": "1063",
          "hp": "636",
          "atk": "304",
          "def": "330",
          "sp": "100",
          "spd": "115",
          "maxpower": "15062",
          "maxhp": "9080",
          "maxatk": "4340",
          "maxdef": "4712",
          "maxsp": "1428",
          "maxspd": "428",
          "skillname": "Special Damage up & Heal",
          "skill": "Increases Special dmg by 39% & Heals all allies's HP by 29%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%",
          "skillimg": "SPECIALDMGup",
     },
     {
          "id": "20138",
          "name": "Juri, Holy Night Thoughtful Lady",
          "type": "red",
          "class": "SP",
          "rare": "5",
          "power": "1063",
          "hp": "601",
          "atk": "100",
          "def": "248",
          "sp": "403",
          "spd": "117",
          "maxpower": "15057",
          "maxhp": "8580",
          "maxatk": "1428",
          "maxdef": "3540",
          "maxsp": "5756",
          "maxspd": "434",
          "skillname": "SP dmg up & Special Taken dmg down",
          "skill": "Equipped unit's column's SP +39% & Equipped unit's Special dmg taken -24%<br><hz>Duration:</hz> 2 turns/3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "SPDMGup",
     },
     {
          "id": "20139",
          "name": "Koto, Holy Night Fiery Lady",
          "type": "green",
          "class": "ATK",
          "rare": "5",
          "power": "1064",
          "hp": "482",
          "atk": "530",
          "def": "180",
          "sp": "101",
          "spd": "120",
          "maxpower": "15062",
          "maxhp": "6884",
          "maxatk": "7568",
          "maxdef": "2568",
          "maxsp": "1440",
          "maxspd": "446",
          "skillname": "ATK up & DEF up",
          "skill": "Equipped unit's ATK +39% & all allies's DEF +24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "ATKup",
     },
     {
          "id": "20145",
          "name": "Botan, Relaxing Guide",
          "type": "green",
          "class": "SP",
          "rare": "5",
          "power": "1065",
          "hp": "592",
          "atk": "100",
          "def": "249",
          "sp": "408",
          "spd": "121",
          "maxpower": "15077",
          "maxhp": "8448",
          "maxatk": "1428",
          "maxdef": "3552",
          "maxsp": "5828",
          "maxspd": "450",
          "skillname": "Critical Rate & SP up",
          "skill": "Equipped unit's column's Critical Rate +33% & Equipped unit's SP +24%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 100%",
          "skillimg": "CRITup",
     },
     {
          "id": "20146",
          "name": "Keiko Yukimura, Relaxing Maiden",
          "type": "red",
          "class": "DEF",
          "rare": "5",
          "power": "1063",
          "hp": "641",
          "atk": "202",
          "def": "327",
          "sp": "202",
          "spd": "116",
          "maxpower": "15047",
          "maxhp": "9152",
          "maxatk": "2880",
          "maxdef": "4668",
          "maxsp": "2880",
          "maxspd": "432",
          "skillname": "Silence & DEF down",
          "skill": "100% chance to Silence all enemies and reduce their DEF by 39%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> 3 turns after the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "DEFdown",
     },
    {
          "id": "20148",
          "name": "Shizuru Kuwabara, Relaxing Elder Sister",
          "type": "red",
          "class": "SP",
          "rare": "5",
          "power": "1064",
          "hp": "464",
          "atk": "102",
          "def": "179",
          "sp": "539",
          "spd": "121",
          "maxpower": "15057",
          "maxhp": "6624",
          "maxatk": "1452",
          "maxdef": "2556",
          "maxsp": "7692",
          "maxspd": "450",
          "skillname": "Critical Damage & DEF up",
          "skill": "Equipped unit's column Critical DMG +50% & DEF +20%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "CRITDMGup",
     },
     {
          "id": "20150",
          "name": "Hiei, Untalkative Waiter",
          "type": "dark",
          "class": "SP",
          "rare": "5",
          "power": "536",
          "hp": "235",
          "atk": "53",
          "def": "104",
          "sp": "256",
          "spd": "62",
          "maxpower": "6462",
          "maxhp": "2853",
          "maxatk": "643",
          "maxdef": "1262",
          "maxsp": "3108",
          "maxspd": "230",
          "skillname": "SP Up",
          "skill": "Increases SP of equipped unit by 10%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "SPup",
     },
     {
          "id": "20151",
          "name": "Kurama, Beautiful Waiter",
          "type": "red",
          "class": "ATK",
          "rare": "5",
          "power": "536",
          "hp": "238",
          "atk": "252",
          "def": "107",
          "sp": "52",
          "spd": "61",
          "maxpower": "6448",
          "maxhp": "2887",
          "maxatk": "3057",
          "maxdef": "1296",
          "maxsp": "629",
          "maxspd": "228",
          "skillname": "ATK Up",
          "skill": "Increases ATK of equipped unit by 10%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "ATKup",
     },
     {
          "id": "20149",
          "name": "Yusuke Urameshi, Lively Waiter",
          "type": "green",
          "class": "DEF",
          "rare": "5",
          "power": "536",
          "hp": "296",
          "atk": "53",
          "def": "172",
          "sp": "157",
          "spd": "60",
          "maxpower": "6452",
          "maxhp": "3591",
          "maxatk": "643",
          "maxdef": "2088",
          "maxsp": "1904",
          "maxspd": "224",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 20%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 100%/1 times",
          "skillimg": "HEAL",
     },
     {
          "id": "20152",
          "name": "Kazuma Kuwabara, Passionate Waiter",
          "type": "blue",
          "class": "DEF",
          "rare": "5",
          "power": "534",
          "hp": "290",
          "atk": "160",
          "def": "172",
          "sp": "52",
          "spd": "59",
          "maxpower": "6436",
          "maxhp": "3519",
          "maxatk": "1938",
          "maxdef": "2088",
          "maxsp": "629",
          "maxspd": "218",
          "skillname": "DEF up",
          "skill": "Increases DEF of equipped unit by 10%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "DEFup",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 4 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20003",
          "name": "Koenma, Enma's Son",
          "type": "blue",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "192",
          "atk": "252",
          "def": "84",
          "sp": "48",
          "spd": "112",
          "maxpower": "5781",
          "maxhp": "2296",
          "maxatk": "3014",
          "maxdef": "1005",
          "maxsp": "574",
          "maxspd": "404",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 62%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20006",
          "name": "Atsuko Urameshi, Bad Housewife",
          "type": "red",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "240",
          "atk": "192",
          "def": "120",
          "sp": "48",
          "spd": "119",
          "maxpower": "5785",
          "maxhp": "2874",
          "maxatk": "2296",
          "maxdef": "1435",
          "maxsp": "574",
          "maxspd": "430",
          "skillname": "Critical Up",
          "skill": "Increases Critical Rate of equipped unit by 30%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a weakening effect <hz>Chance:</hz> 72%",
          "skillimg": "CRITup",
     },
     
     {
          "id": "20012",
          "name": "Ayame, Secret Feelings",
          "type": "dark",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "96",
          "def": "156",
          "sp": "96",
          "spd": "119",
          "maxpower": "5777",
          "maxhp": "3157",
          "maxatk": "1145",
          "maxdef": "1866",
          "maxsp": "1145",
          "maxspd": "430",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 34%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20014",
          "name": "Shizuru Kuwabara, Spirit Sensing Elder Sister",
          "type": "green",
          "class": "SP",
          "rare": "4",
          "power": "491",
          "hp": "216",
          "atk": "48",
          "def": "96",
          "sp": "228",
          "spd": "116",
          "maxpower": "5779",
          "maxhp": "2583",
          "maxatk": "574",
          "maxsp": "1145",
          "maxdef": "2727",
          "maxspd": "418",
          "skillname": "SP up",
          "skill": "Increases SP of equipped unit by 37%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 72%",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20051",
          "name": "Puu, Words of the Master",
          "type": "light",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "48",
          "def": "156",
          "sp": "144",
          "spd": "114",
          "maxpower": "5781",
          "maxhp": "3157",
          "maxatk": "574",
          "maxdef": "1866",
          "maxsp": "1722",
          "maxspd": "410",
          "skillname": "ATK Damage Resistance",
          "skill": "Increases Resistance of equipped row against ATK Damage taken by 47%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKDMGresist",
     },
     
     {
          "id": "20094",
          "name": "Botan, Amulet Costume",
          "type": "green",
          "class": "DEF",
          "rare": "4",
          "power": "411",
          "hp": "220",
          "atk": "120",
          "def": "130",
          "sp": "40",
          "spd": "112",
          "maxpower": "4141",
          "maxhp": "2256",
          "maxatk": "1230",
          "maxdef": "1332",
          "maxsp": "411",
          "maxspd": "404",
          "skillname": "Defense up",
          "skill": "Increases DEF of equipped row by 40%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 90%",
          "skillimg": "DEFup",
     },
     {
          "id": "20097",
          "name": "Ruka, Holy Night Charming Lady",
          "type": "dark",
          "class": "DEF",
          "rare": "4",
          "power": "411",
          "hp": "224",
          "atk": "40",
          "def": "131",
          "sp": "118",
          "spd": "109",
          "maxpower": "4150",
          "maxhp": "2295",
          "maxatk": "411",
          "maxdef": "1341",
          "maxsp": "1212",
          "maxspd": "392",
          "skillname": "Guard Percentage Up",
          "skill": "Increases guard percentage of own row by 17%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 90%",
          "skillimg": "GUARDup",
     },
     {
          "id": "20099",
          "name": "Toguro, Strength Seeker",
          "type": "red",
          "class": "ATK",
          "rare": "4",
          "power": "413",
          "hp": "200",
          "atk": "161",
          "def": "101",
          "sp": "40",
          "spd": "118",
          "maxpower": "4167",
          "maxhp": "2052",
          "maxatk": "1653",
          "maxdef": "1035",
          "maxsp": "411",
          "maxspd": "426",
          "skillname": "ATK Damage Resistance Down",
          "skill": "30% chance to reduce enemy's front column's ATK damage resistance by 24%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 72%",
          "skillimg": "ATKDMGresistdown",
     },
     {
          "id": "20100",
          "name": "Genkai, Brilliant Spirit Seeker",
          "type": "blue",
          "class": "SP",
          "rare": "4",
          "power": "410",
          "hp": "203",
          "atk": "40",
          "def": "100",
          "sp": "157",
          "spd": "117",
          "maxpower": "4126",
          "maxhp": "2079",
          "maxatk": "411",
          "maxdef": "1026",
          "maxsp": "1608",
          "maxspd": "422",
          "skillname": "SP Damage Resistance Down",
          "skill": "30% chance to reduce enemy's front column's SP damage resistance by 24%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 72%",
          "skillimg": "SPDMGresistdown",
     },
     {
          "id": "20108",
          "name": "Yukina, Summer Snow Lady",
          "type": "light",
          "class": "DEF",
          "rare": "4",
          "power": "413",
          "hp": "220",
          "atk": "81",
          "def": "132",
          "sp": "79",
          "spd": "117",
          "maxpower": "4158",
          "maxhp": "2256",
          "maxatk": "828",
          "maxdef": "1350",
          "maxsp": "810",
          "maxspd": "422",
          "skillname": "HP Regeneration",
          "skill": "Heals equipped unit by 5%<br><hz>Duration:</hz> 5 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "REGEN",
     },
     {
          "id": "20147",
          "name": "Atsuko Urameshi, Relaxing Housewife",
          "type": "blue",
          "class": "ATK",
          "rare": "4",
          "power": "415",
          "hp": "167",
          "atk": "212",
          "def": "69",
          "sp": "39",
          "spd": "116",
          "maxpower": "4175",
          "maxhp": "1710",
          "maxatk": "2175",
          "maxdef": "708",
          "maxsp": "396",
          "maxspd": "418",
          "skillname": "DEF down",
          "skill": "100% chance to decrese all enemies DEF by 10%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP goes under 50% <hz>Chance:</hz> 100%",
          "skillimg": "DEFdown",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 3 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20004",
          "name": "Sayaka, Spirit World Agent",
          "type": "light",
          "class": "DEF",
          "rare": "3",
          "power": "372",
          "hp": "198",
          "atk": "72",
          "def": "117",
          "sp": "72",
          "spd": "125",
          "maxpower": "3567",
          "maxhp": "1941",
          "maxatk": "702",
          "maxdef": "1149",
          "maxsp": "702",
          "maxspd": "436",
          "skillname": "HEAL",
          "skill": "Heals equipped unit's HP by 30%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 70%/1 time",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20011",
          "name": "George Saotome, Honest Assistant",
          "type": "blue",
          "class": "SP",
          "rare": "3",
          "power": "371",
          "hp": "180",
          "atk": "36",
          "def": "90",
          "sp": "144",
          "spd": "112",
          "maxpower": "3564",
          "maxhp": "1764",
          "maxatk": "351",
          "maxdef": "882",
          "maxsp": "1410",
          "maxspd": "392",
          "skillname": "Sp Up",
          "skill": "Increases SP of equipped unit by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20017",
          "name": "Puu, Spirit Beast",
          "type": "red",
          "class": "DEF",
          "rare": "3",
          "power": "371",
          "hp": "198",
          "atk": "108",
          "def": "117",
          "sp": "36",
          "spd": "114",
          "maxpower": "3569",
          "maxhp": "1941",
          "maxatk": "1059",
          "maxsp": "1149",
          "maxdef": "351",
          "maxspd": "400",
          "skillname": "Sp Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against SP damage taken by 54%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "SPDMGresist",
     },
     
     {
          "id": "20026",
          "name": "Shiori Minamino, Gentle Mother",
          "type": "green",
          "class": "DEF",
          "rare": "3",
          "power": "372",
          "hp": "198",
          "atk": "72",
          "def": "117",
          "sp": "72",
          "spd": "124",
          "maxpower": "3566",
          "maxhp": "1941",
          "maxatk": "702",
          "maxdef": "1149",
          "maxsp": "702",
          "maxspd": "434",
          "skillname": "Defense Up",
          "skill": "Increases DEF of equipped unit by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20054",
          "name": "Botan, Spirit Detective Assistant",
          "type": "dark",
          "class": "DEF",
          "rare": "3",
          "power": "373",
          "hp": "201",
          "atk": "35",
          "def": "117",
          "sp": "109",
          "spd": "116",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxdef": "-",
          "maxsp": "-",
          "maxspd": "-",
          "skillname": "HP Regeneration",
          "skill": "Heals equipped unit's HP by 10%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "REGEN",
     },

     {
          "id": "20058",
          "name": "Hagiri's Younger Sister, Psychometry",
          "type": "dark",
          "class": "ATK",
          "rare": "3",
          "power": "371",
          "hp": "161",
          "atk": "72",
          "def": "171",
          "sp": "36",
          "spd": "116",
          "maxpower": "3562",
          "maxhp": "1590",
          "maxatk": "1674",
          "maxdef": "702",
          "maxsp": "351",
          "maxspd": "406",
          "skillname": "Defense Down",
          "skill": "80% chance of decreasing target's DEF by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "DEFdown",
     },

     {
          "id": "20102",
          "name": "Masaru, Energetic Boy",
          "type": "blue",
          "class": "ATK",
          "rare": "3",
          "power": "374",
          "hp": "163",
          "atk": "173",
          "def": "72",
          "sp": "36",
          "spd": "121",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxdef": "-",
          "maxsp": "-",
          "maxspd": "-",
          "skillname": "ATK up",
          "skill": "Increases own row's ATK by 15%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },

     {
          "id": "20103",
          "name": "Masaru's Mom, Kind Sincerity",
          "type": "red",
          "class": "SP",
          "rare": "3",
          "power": "369",
          "hp": "176",
          "atk": "35",
          "def": "90",
          "sp": "145",
          "spd": "117",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxdef": "-",
          "maxsp": "-",
          "maxspd": "-",
          "skillname": "SP up",
          "skill": "Increases own row's SP by 15%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "SPup",
     },

     {
          "id": "20112",
          "name": "Yusuke Urameshi, Little Promise",
          "type": "green",
          "class": "ATK",
          "rare": "3",
          "power": "373",
          "hp": "182",
          "atk": "145",
          "def": "90",
          "sp": "36",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxdef": "-",
          "maxsp": "-",
          "maxspd": "-",
          "skillname": "Damage up",
          "skill": "Increases equipped unit's Damage given by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%",
          "skillimg": "DMGup",
     },

     {
          "id": "20113",
          "name": "Keiko Yukimura, Little Wish",
          "type": "light",
          "class": "SP",
          "rare": "3",
          "power": "371",
          "hp": "160",
          "atk": "36",
          "def": "72",
          "sp": "172",
          "spd": "116",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxdef": "-",
          "maxsp": "-",
          "maxspd": "-",
          "skillname": "Damage up",
          "skill": "Increases equipped unit's Damage given by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%",
          "skillimg": "DMGup",
     },
     {
          "id": "20144",
          "name": "Beautiful Suzuki, Rainbow-Colored Legend",
          "type": "green",
          "class": "SP",
          "rare": "3",
          "power": "373",
          "hp": "182",
          "atk": "36",
          "def": "90",
          "sp": "145",
          "spd": "117",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxdef": "-",
          "maxsp": "-",
          "maxspd": "-",
          "skillname": "SP Down",
          "skill": "41% Chance to reduce enemy's back row's SP by 41%<br><hz>Duration:</hz> 4 turns <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 41%/1 time",
          "skillimg": "SPdown",
     },

            // -------------------------------------------------------------------------------- 
                                              // 2 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20018",
          "name": "Muguru, Bird Demon",
          "type": "red",
          "class": "SP",
          "rare": "2",
          "power": "292",
          "hp": "126",
          "atk": "26",
          "def": "56",
          "sp": "133",
          "spd": "128",
          "maxpower": "2657",
          "maxhp": "1179",
          "maxatk": "261",
          "maxdef": "522",
          "maxsp": "1242",
          "maxspd": "434",
          "skillname": "SP Damage Resistance Down",
          "skill": "80% chance of decreasing target's resistance against SP damage taken by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "SPDMGresistdown",
     },
     
     {
          "id": "20029",
          "name": "Okubo, Kuwabara's Underling",
          "type": "dark",
          "class": "DEF",
          "rare": "2",
          "power": "291",
          "hp": "154",
          "atk": "56",
          "def": "91",
          "sp": "56",
          "spd": "113",
          "maxpower": "2654",
          "maxhp": "1440",
          "maxatk": "522",
          "maxdef": "852",
          "maxsp": "522",
          "maxspd": "384",
          "skillname": "Def Up",
          "skill": "Increases DEF of equipped unit by 35%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20030",
          "name": "Kirishima, Kuwabara's Underling",
          "type": "green",
          "class": "ATK",
          "rare": "2",
          "power": "291",
          "hp": "140",
          "atk": "112",
          "def": "70",
          "sp": "28",
          "spd": "119",
          "maxpower": "2654",
          "maxhp": "1311",
          "maxatk": "1044",
          "maxdef": "654",
          "maxsp": "261",
          "maxspd": "404",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 35%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20031",
          "name": "Sawamura, Kuwabara's Underling",
          "type": "light",
          "class": "DEF",
          "rare": "2",
          "power": "292",
          "hp": "154",
          "atk": "56",
          "def": "91",
          "sp": "56",
          "spd": "126",
          "maxpower": "2658",
          "maxhp": "1440",
          "maxatk": "522",
          "maxdef": "852",
          "maxsp": "522",
          "maxspd": "428",
          "skillname": "Def Up",
          "skill": "Increases DEF of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a weakening effect <hz>Chance:</hz> 64%",
          "skillimg": "DEFup",
     },
     {
          "id": "20044",
          "name": "Seller Duff, Merchant",
          "type": "light",
          "class": "ATK",
          "rare": "2",
          "power": "290",
          "hp": "139",
          "atk": "112",
          "def": "69",
          "sp": "28",
          "spd": "118",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a decreasing effect <hz>Chance:</hz> 64%",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20045",
          "name": "Ship's Captain, Guide",
          "type": "blue",
          "class": "ATK",
          "rare": "2",
          "power": "291",
          "hp": "126",
          "atk": "133",
          "def": "56",
          "sp": "28",
          "spd": "111",
          "maxpower": "2651",
          "maxhp": "1179",
          "maxatk": "1242",
          "maxdef": "522",
          "maxsp": "261",
          "maxspd": "374",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when an ally dies <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },

     {
          "id": "20101",
          "name": "Slime Youkai, Verdict Apparition",
          "type": "red",
          "class": "DEF",
          "rare": "2",
          "power": "291",
          "hp": "126",
          "atk": "133",
          "def": "56",
          "sp": "28",
          "spd": "111",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Damage Reduction",
          "skill": "Reduces Damage taken of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP goes under 30% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "DMGresist",
     },

     {
          "id": "20109",
          "name": "Imp, Evil Whisperer",
          "type": "green",
          "class": "SP",
          "rare": "2",
          "power": "286",
          "hp": "123",
          "atk": "27",
          "def": "55",
          "sp": "131",
          "spd": "120",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "SP up",
          "skill": "Increases SP of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when an ally dies <hz>Chance:</hz> 80%",
          "skillimg": "SPup",
     },

     {
          "id": "20110",
          "name": "Familiar, Servant of Shadows",
          "type": "blue",
          "class": "SP",
          "rare": "2",
          "power": "290",
          "hp": "139",
          "atk": "27",
          "def": "70",
          "sp": "112",
          "spd": "121",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Critical up",
          "skill": "Increases Critical Rate of equipped unit by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP goes under 50% <hz>Chance:</hz> 80%",
          "skillimg": "CRITup",
     },

     {
          "id": "20111",
          "name": "Dr.Ichigaki, Evil Scientist",
          "type": "dark",
          "class": "DEF",
          "rare": "2",
          "power": "291",
          "hp": "154",
          "atk": "84",
          "def": "91",
          "sp": "28",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "SP Damage Resistance Up",
          "skill": "Increases SP Damage resistance of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when under a status effect <hz>Chance:</hz> 80%",
          "skillimg": "SPDMGresist",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 1 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20005",
          "name": "Takenaka, Model Teacher",
          "type": "red",
          "class": "ATK",
          "rare": "1",
          "power": "252",
          "hp": "120",
          "atk": "96",
          "def": "60",
          "sp": "24",
          "spd": "121",
          "maxpower": "2172",
          "maxhp": "1068",
          "maxatk": "855",
          "maxdef": "531",
          "maxsp": "213",
          "maxspd": "396",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20015",
          "name": "Eikichi, Kuwabara's Best Friend",
          "type": "light",
          "class": "ATK",
          "rare": "1",
          "power": "252",
          "hp": "108",
          "atk": "114",
          "def": "48",
          "sp": "24",
          "spd": "126",
          "maxpower": "2177",
          "maxhp": "960",
          "maxatk": "1014",
          "maxdef": "429",
          "maxsp": "213",
          "maxspd": "412",
          "skillname": "Atk Damage Resistance Down",
          "skill": "80% chance of decreasing enemy's resistance against ATK damage by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "ATKDMGresistdown",
     },
     
     {
          "id": "20025",
          "name": "Little Girl, The Saved One",
          "type": "blue",
          "class": "DEF",
          "rare": "1",
          "power": "251",
          "hp": "132",
          "atk": "72",
          "def": "78",
          "sp": "24",
          "spd": "116",
          "maxpower": "2171",
          "maxhp": "1176",
          "maxatk": "639",
          "maxdef": "693",
          "maxsp": "213",
          "maxspd": "380",
          "skillname": "Atk Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against ATK damage taken by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "ATKDMGresist",
     },
     
     {
          "id": "20027",
          "name": "Iwamoto, Bad Teacher",
          "type": "dark",
          "class": "SP",
          "rare": "1",
          "power": "251",
          "hp": "108",
          "atk": "24",
          "def": "48",
          "sp": "114",
          "spd": "116",
          "maxpower": "2174",
          "maxhp": "960",
          "maxatk": "213",
          "maxdef": "429",
          "maxsp": "1014",
          "maxspd": "380",
          "skillname": "Atk Up",
          "skill": "Increases SP of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20028",
          "name": "Akashi, Minion",
          "type": "green",
          "class": "DEF",
          "rare": "1",
          "power": "251",
          "hp": "132",
          "atk": "24",
          "def": "78",
          "sp": "72",
          "spd": "111",
          "maxpower": "2169",
          "maxhp": "1176",
          "maxatk": "213",
          "maxdef": "693",
          "maxsp": "639",
          "maxspd": "364",
          "skillname": "Atk Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against ATK damage taken by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when under a status condition <hz>Chance:</hz> 80%",
          "skillimg": "ATKDMGresist",
     },
     
] 
