window.support=[
     
            // -------------------------------------------------------------------------------- 
                                              // 5 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20001",
          "name": "Keiko Yukimura, Goddess of Victory",
          "type": "heart",
          "class": "ATK",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "400",
          "def": "250",
          "sp": "100",
          "spd": "121",
          "maxpower": "14327",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxsp": "1428",
          "maxdef": "3572",
          "maxspd": "450",
          "skillname": "ATK up",
          "skill": "Increases ATK of equipped unit by 80%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     {
          "id": "20002",
          "name": "Botan, Spiritual Guide",
          "type": "yang",
          "class": "SP",
          "rare": "5",
          "power": "1011",
          "hp": "400",
          "atk": "100",
          "def": "175",
          "sp": "525",
          "spd": "111",
          "maxpower": "14317",
          "maxhp": "7496",
          "maxatk": "1428",
          "maxdef": "1428",
          "maxsp": "5712",
          "maxspd": "412",
          "skillname": "SP up",
          "skill": "Increases SP of equipped column by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20013",
          "name": "Great King Enma, Spirit World Ruler",
          "type": "yin",
          "class": "ATK",
          "rare": "5",
          "power": "1011",
          "hp": "500",
          "atk": "400",
          "def": "250",
          "sp": "100",
          "spd": "111",
          "maxpower": "14323",
          "maxhp": "7140",
          "maxatk": "5712",
          "maxdef": "3572",
          "maxsp": "1428",
          "maxspd": "412",
          "skillname": "ATK up",
          "skill": "Increases ATK of equipped column by 24%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20016",
          "name": "Yukina, Dearly Prayer",
          "type": "body",
          "class": "DEF",
          "rare": "5",
          "power": "1011",
          "hp": "550",
          "atk": "200",
          "def": "325",
          "sp": "200",
          "spd": "119",
          "maxpower": "14324",
          "maxhp": "7856",
          "maxatk": "2856",
          "maxsp": "2856",
          "maxdef": "4640",
          "maxspd": "444",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 43%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 100%",
          "skillimg": "HEAL",
     },
     {
          "id": "20019",
          "name": "Sakyo, A Game of Aesthetics",
          "type": "yin",
          "class": "SP",
          "rare": "5",
          "power": "1012",
          "hp": "500",
          "atk": "100",
          "def": "250",
          "sp": "400",
          "spd": "126",
          "maxpower": "14328",
          "maxhp": "7140",
          "maxatk": "1428",
          "maxsp": "5712",
          "maxdef": "3572",
          "maxspd": "468",
          "skillname": "Defense Down",
          "skill": "Decreases DEF of front enemy column by 43%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 80%",
          "skillimg": "DEFdown",
     },
     {
          "id": "20020",
          "name": "Koto, Fiery Commentary",
          "type": "body",
          "class": "SP",
          "rare": "5",
          "power": "1005",
          "hp": "495",
          "atk": "102",
          "def": "252",
          "sp": "392",
          "spd": "117",
          "maxpower": "14217",
          "maxhp": "7068",
          "maxatk": "1452",
          "maxsp": "3596",
          "maxdef": "5592",
          "maxspd": "434",
          "skillname": "SP Damage Resistance Down",
          "skill": "80% chance to reduce enemy's front column's SP damage resistance by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a strengthening effect <hz>Chance:</hz> 80%",
          "skillimg": "SPDMGresistdown",
     },
     {
          "id": "20024",
          "name": "Koenma (Youth), Spirit World Royalty",
          "type": "dex",
          "class": "DEF",
          "rare": "5",
          "power": "1012",
          "hp": "550",
          "atk": "100",
          "def": "325",
          "sp": "300",
          "spd": "120",
          "maxpower": "14324",
          "maxhp": "7856",
          "maxatk": "1428",
          "maxsp": "4284",
          "maxdef": "4640",
          "maxspd": "446",
          "skillname": "Ressurection",
          "skill": "Revives equipped unit with 29% HP<br><hz>Duration:</hz> instant <hz>Condition:</hz> upon death <hz>Chance:</hz> 100%/1 time",
          "skillimg": "REVIVE",
     },
     {
          "id": "20095",
          "name": "Keiko Yukimura, Holy Night Lovely Lady",
          "type": "heart",
          "class": "SP",
          "rare": "5",
          "power": "1008",
          "hp": "441",
          "atk": "99",
          "def": "202",
          "sp": "475",
          "spd": "123",
          "maxpower": "14265",
          "maxhp": "6296",
          "maxatk": "1412",
          "maxdef": "2880",
          "maxsp": "6780",
          "maxspd": "456",
          "skillname": "Sp Up",
          "skill": "Increases equipped unit's SP by 51%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 80%",
          "skillimg": "SPup",
     },
     {
          "id": "20096",
          "name": "Yukina, Holy Night Snow Lady",
          "type": "dex",
          "class": "DEF",
          "rare": "5",
          "power": "1015",
          "hp": "555",
          "atk": "303",
          "def": "325",
          "sp": "98",
          "spd": "118",
          "maxpower": "14373",
          "maxhp": "7920",
          "maxatk": "4328",
          "maxdef": "4640",
          "maxsp": "1400",
          "maxspd": "438",
          "skillname": "HP Regeneration",
          "skill": "Heals own column by 20%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 100%",
          "skillimg": "HEAL",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 4 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20003",
          "name": "Koenma, Enma's Son",
          "type": "body",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "192",
          "atk": "252",
          "def": "84",
          "sp": "48",
          "spd": "112",
          "maxpower": "5781",
          "maxhp": "2296",
          "maxatk": "3014",
          "maxdef": "1005",
          "maxsp": "574",
          "maxspd": "404",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 62%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20006",
          "name": "Atsuko Urameshi, Bad Housewife",
          "type": "heart",
          "class": "ATK",
          "rare": "4",
          "power": "491",
          "hp": "240",
          "atk": "192",
          "def": "120",
          "sp": "48",
          "spd": "119",
          "maxpower": "5785",
          "maxhp": "2874",
          "maxatk": "2296",
          "maxdef": "1435",
          "maxsp": "574",
          "maxspd": "430",
          "skillname": "Critical Up",
          "skill": "Increases Critical Rate of equipped unit by 30%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 72%",
          "skillimg": "CRITup",
     },
     
     {
          "id": "20012",
          "name": "Ayame, Secret Feelings",
          "type": "yin",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "96",
          "def": "156",
          "sp": "96",
          "spd": "119",
          "maxpower": "5777",
          "maxhp": "3157",
          "maxatk": "1145",
          "maxdef": "1866",
          "maxsp": "1145",
          "maxspd": "430",
          "skillname": "Heal",
          "skill": "Heals equipped unit's HP by 34%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20014",
          "name": "Shizuru Kuwabara, Spirit Sensing Elder Sister",
          "type": "dex",
          "class": "SP",
          "rare": "4",
          "power": "491",
          "hp": "216",
          "atk": "48",
          "def": "96",
          "sp": "228",
          "spd": "116",
          "maxpower": "5779",
          "maxhp": "2583",
          "maxatk": "574",
          "maxsp": "1145",
          "maxdef": "2727",
          "maxspd": "418",
          "skillname": "SP up",
          "skill": "Increases SP of equipped unit by 37%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after defeating an enemy <hz>Chance:</hz> 72%",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20051",
          "name": "Puu, Words of the Master",
          "type": "yang",
          "class": "DEF",
          "rare": "4",
          "power": "491",
          "hp": "264",
          "atk": "48",
          "def": "156",
          "sp": "144",
          "spd": "114",
          "maxpower": "5781",
          "maxhp": "3157",
          "maxatk": "574",
          "maxdef": "1866",
          "maxsp": "1722",
          "maxspd": "410",
          "skillname": "ATK Damage Resistance",
          "skill": "Increases Resistance of equipped row against ATK Damage taken by 47%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 90%/1 time",
          "skillimg": "ATKDMGresist",
     },
     
     {
          "id": "20094",
          "name": "Botan, Amulet Costume",
          "type": "dex",
          "class": "DEF",
          "rare": "4",
          "power": "411",
          "hp": "220",
          "atk": "120",
          "def": "130",
          "sp": "40",
          "spd": "112",
          "maxpower": "4141",
          "maxhp": "2256",
          "maxatk": "1230",
          "maxdef": "1332",
          "maxsp": "411",
          "maxspd": "404",
          "skillname": "Defense up",
          "skill": "Increases DEF of equipped row by 40%<br><hz>Duration:</hz> 2 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 90%",
          "skillimg": "DEFup",
     },
     {
          "id": "20097",
          "name": "Ruka, Holy Night Charming Lady",
          "type": "yin",
          "class": "DEF",
          "rare": "4",
          "power": "411",
          "hp": "224",
          "atk": "40",
          "def": "131",
          "sp": "118",
          "spd": "109",
          "maxpower": "4150",
          "maxhp": "2295",
          "maxatk": "411",
          "maxdef": "1341",
          "maxsp": "1212",
          "maxspd": "392",
          "skillname": "Guard Up",
          "skill": "Increases guard percentage of own row by 17%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 90%",
          "skillimg": "GUARDup",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 3 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20004",
          "name": "Sayaka, Spirit World Agent",
          "type": "yang",
          "class": "DEF",
          "rare": "3",
          "power": "372",
          "hp": "198",
          "atk": "72",
          "def": "117",
          "sp": "72",
          "spd": "125",
          "maxpower": "3567",
          "maxhp": "1941",
          "maxatk": "702",
          "maxdef": "1149",
          "maxsp": "702",
          "maxspd": "436",
          "skillname": "HEAL",
          "skill": "Heals equipped unit's HP by 30%<br><hz>Duration:</hz> instant <hz>Condition:</hz> when HP is under 30% <hz>Chance:</hz> 70%/1 time",
          "skillimg": "HEAL",
     },
     
     {
          "id": "20011",
          "name": "George Saotome, Honest Assistant",
          "type": "body",
          "class": "SP",
          "rare": "3",
          "power": "371",
          "hp": "180",
          "atk": "36",
          "def": "90",
          "sp": "144",
          "spd": "112",
          "maxpower": "3564",
          "maxhp": "1764",
          "maxatk": "351",
          "maxdef": "882",
          "maxsp": "1410",
          "maxspd": "392",
          "skillname": "Sp Up",
          "skill": "Increases SP of equipped unit by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20017",
          "name": "Puu, Spirit Beast",
          "type": "heart",
          "class": "DEF",
          "rare": "3",
          "power": "371",
          "hp": "198",
          "atk": "108",
          "def": "117",
          "sp": "36",
          "spd": "114",
          "maxpower": "3569",
          "maxhp": "1941",
          "maxatk": "1059",
          "maxsp": "1149",
          "maxdef": "351",
          "maxspd": "400",
          "skillname": "Sp Damage Resistance",
          "skill": "Increases resistance of equipped unit against SP damage taken by 54%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "SPDMGresist",
     },
     
     {
          "id": "20026",
          "name": "Shiori Minamino, Gentle Mother",
          "type": "dex",
          "class": "DEF",
          "rare": "3",
          "power": "372",
          "hp": "198",
          "atk": "72",
          "def": "117",
          "sp": "72",
          "spd": "124",
          "maxpower": "3566",
          "maxhp": "1941",
          "maxatk": "702",
          "maxdef": "1149",
          "maxsp": "702",
          "maxspd": "434",
          "skillname": "Defense Up",
          "skill": "Increases DEF of equipped unit by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20058",
          "name": "Hagiri's Younger Sister, Psychometry",
          "type": "yin",
          "class": "ATK",
          "rare": "3",
          "power": "371",
          "hp": "161",
          "atk": "72",
          "def": "171",
          "sp": "36",
          "spd": "116",
          "maxpower": "3562",
          "maxhp": "1590",
          "maxatk": "1674",
          "maxdef": "702",
          "maxsp": "351",
          "maxspd": "406",
          "skillname": "Defense Down",
          "skill": "80% chance of decreasing target's DEF by 33%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "DEFdown",
     },
            // -------------------------------------------------------------------------------- 
                                              // 2 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20018",
          "name": "Muguru, Bird Demon",
          "type": "heart",
          "class": "SP",
          "rare": "2",
          "power": "292",
          "hp": "126",
          "atk": "26",
          "def": "56",
          "sp": "133",
          "spd": "128",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "SP Damage Resistance Down",
          "skill": "80% chance of decreasing target's resistance against SP damage taken by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "SPDMGresistdown",
     },
     
     {
          "id": "20029",
          "name": "Okubo, Kuwabara's Underling",
          "type": "yin",
          "class": "DEF",
          "rare": "2",
          "power": "291",
          "hp": "154",
          "atk": "56",
          "def": "91",
          "sp": "56",
          "spd": "113",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Def Up",
          "skill": "Increases DEF of equipped unit by 35%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20030",
          "name": "Kirishima, Kuwabara's Underling",
          "type": "dex",
          "class": "ATK",
          "rare": "2",
          "power": "291",
          "hp": "140",
          "atk": "112",
          "def": "70",
          "sp": "28",
          "spd": "119",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 35%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when HP is under 50% <hz>Chance:</hz> 80%/1 time",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20031",
          "name": "Sawamura, Kuwabara's Underling",
          "type": "yang",
          "class": "DEF",
          "rare": "2",
          "power": "292",
          "hp": "154",
          "atk": "56",
          "def": "91",
          "sp": "56",
          "spd": "126",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Def Up",
          "skill": "Increases DEF of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "DEFup",
     },
     
     {
          "id": "20045",
          "name": "Ship's Captain, Guide",
          "type": "body",
          "class": "ATK",
          "rare": "2",
          "power": "291",
          "hp": "126",
          "atk": "133",
          "def": "56",
          "sp": "28",
          "spd": "111",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when an ally dies <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     
            // -------------------------------------------------------------------------------- 
                                              // 1 STAR CARDS
            // -------------------------------------------------------------------------------- 
     
     {
          "id": "20005",
          "name": "Takenaka, Model Teacher",
          "type": "heart",
          "class": "ATK",
          "rare": "1",
          "power": "252",
          "hp": "120",
          "atk": "96",
          "def": "60",
          "sp": "24",
          "spd": "121",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Up",
          "skill": "Increases ATK of equipped unit by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> at the start of the WAVE <hz>Chance:</hz> 80%",
          "skillimg": "ATKup",
     },
     
     {
          "id": "20015",
          "name": "Eikichi, Kuwabara's Best Friend",
          "type": "yang",
          "class": "ATK",
          "rare": "1",
          "power": "252",
          "hp": "108",
          "atk": "114",
          "def": "48",
          "sp": "24",
          "spd": "126",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Damage Resistance Down",
          "skill": "80% chance of decreasing enemy's resistance against ATK damage by 21%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when hit by a special <hz>Chance:</hz> 64%",
          "skillimg": "ATKDMGresistdown",
     },
     
     {
          "id": "20025",
          "name": "Little Girl, The Saved One",
          "type": "body",
          "class": "DEF",
          "rare": "1",
          "power": "251",
          "hp": "132",
          "atk": "72",
          "def": "78",
          "sp": "24",
          "spd": "116",
          "maxpower": "2171",
          "maxhp": "1176",
          "maxatk": "639",
          "maxdef": "693",
          "maxsp": "213",
          "maxspd": "380",
          "skillname": "Atk Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against ATK damage taken by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "ATKDMGresist",
     },
     
     {
          "id": "20027",
          "name": "Iwamoto, Bad Teacher",
          "type": "yin",
          "class": "SP",
          "rare": "1",
          "power": "251",
          "hp": "108",
          "atk": "24",
          "def": "48",
          "sp": "114",
          "spd": "116",
          "maxpower": "2174",
          "maxhp": "960",
          "maxatk": "213",
          "maxdef": "429",
          "maxsp": "1014",
          "maxspd": "380",
          "skillname": "Atk Up",
          "skill": "Increases SP of equipped unit by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> after a status decrease <hz>Chance:</hz> 64%",
          "skillimg": "SPup",
     },
     
     {
          "id": "20028",
          "name": "Akashi, Minion",
          "type": "dex",
          "class": "DEF",
          "rare": "1",
          "power": "251",
          "hp": "132",
          "atk": "24",
          "def": "78",
          "sp": "72",
          "spd": "111",
          "maxpower": "-",
          "maxhp": "-",
          "maxatk": "-",
          "maxsp": "-",
          "maxdef": "-",
          "maxspd": "-",
          "skillname": "Atk Damage Resistance Up",
          "skill": "Increases resistance of equipped unit against ATK damage taken by 28%<br><hz>Duration:</hz> 3 turns <hz>Condition:</hz> when under a status condition <hz>Chance:</hz> 80%",
          "skillimg": "ATKDMGresist",
     },
     
] 
