window.chara = [

    {
        "id": "13123",
        "name": "Touya, Refined Ice Attack",
        "type": "Light",
        "class": "SP",
        "rare": "6",
        "power": "40238",
        "hp": "32070",
        "atk": "3000",
        "def": "5259",
        "sp": "15890",
        "spd": "549",
        "maxpower": "15005",
        "maxhp": "6708",
        "maxatk": "1496",
        "maxdef": "2996",
        "maxsp": "7124",
        "maxspd": "358",
        "skill1img": "",
        "skill1name": "Cursed Ice Barrier",
        "skill1": "Inflict Freeze Resistance -50% (3 Turns)<br>Inflict Freeze (1 Turn)<br>SP Damage Taken +60%<br>SPD -20%<br>Inflict ATK, SPD and DEF -50% to Frozen Enemies (3 Turn)",
        "skill1cd": "98",
        "skill2img": "",
        "skill2name": "Cursed Ice Sword・Bind",
        "skill2": "Grant Disable Special Move Penetration to self (1 Turn)<br>Inflict Guard Chance -100% (3 Turns)<br>Inflict Freeze (3 Turns)<br>Inflict 300% SP to one enemy<br>Deal +50% more Damage to Frozen Enemy",
        "skill2cd": "81",
        "autoname1": "Type Advantage Damage",
        "auto1": "Type Avantage Damage +20%<br><hz>Duration:</hz> Permanent <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg1": "CRITup",
        "autoname2": "Freeze Resistance ",
        "auto2": "Freeze Resistance +100%<br><hz>Duration:</hz> Permanent <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg2": "FREEZEresist",
        "autoname3": "Frost Enchantment",
        "auto3": "SP +120%. Inflict ATK, SPD and DEF -50% to Frozen Enemies. Disable Recovery<br><hz>Duration:</hz> 3 Turns <hz>Condition:</hz> Start of the Turn <hz>Chance:</hz> 100%/ Unlimited",
        "autoimg3": "SPup",
        "autoname4": "Damage Up",
        "auto4": "Damage Up +20%<br><hz>Duration:</hz> Permanent <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg4": "DMGup",
        "autoname5": "Damage Reduction ",
        "auto5": "Damage Reduction +20%<br><hz>Duration:</hz> Permanent <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg5": "DMGresist",
        "autoname6": "Potential・Dark Resistance Up",
        "auto6": "Dark Type Resistance +20%<br><hz>Duration:</hz> Permanent <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg6": "DMGresist",
        "autoname7": "Potential・Paralysis Resistance",
        "auto7": "Paralysis Resistance +100%<br><hz>Duration:</hz> Permanent <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg7": "SILENCEresist",
        "autoname8": "Potential・Damage Up",
        "auto8": "Damage Up +20%<br><hz>Duration:</hz> 2 Turns <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg8": "SPup",
        "autoname9": "Great Age・Attack Model",
        "auto9": "Damage Up +20% and Damage Reduction +10%<br><hz>Duration:</hz> Permanent <hz>Condition:</hz> At the start of the battle <hz>Chance:</hz> 100%",
        "autoimg9": "SPup",
        "lead": "Light Attribute SP +30% / DEF +22%",
        "rank": "G"
    },
]